---
# main task yaml import or includes  
#
#
# import_tasks: 
# tags: 

- name: Check for RHEL operating system
  debug:
    msg: "Detected ansible_os_family is {{ ansible_os_family }}"

- import_tasks: t_install_rsyslog.yml
