---
- block:
  - name: Install bit
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
    - rsyslog
    when: ansible_distribution == "RedHat" or ansible_distribution == "CentOs"  
